ArdelsCakeShop/Models/Orders/OrderDetail.cs
using ArdelsCakeShop.Models.Cakes;

namespace ArdelsCakeShop.Models.Orders
{
    public class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int CakeId { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public virtual Cake Cake { get; set; }
        public virtual Order Order { get; set; }
    }
}

ArdelsCakeShop/Models/Orders/OrderState.cs
namespace ArdelsCakeShop.Models.Orders
{    
        public enum OrderState
        {
            Pending,
            Accepted,
            Completed,            
            Rejected
        };    
}

ArdelsCakeShop/Models/Orders/OrdersArchive.cs
using ArdelsCakeShop.Models.IdentityModel;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.ModelBinding;


namespace ArdelsCakeShop.Models.Orders
{
    public class OrdersArchive
    {
        [BindNever]
        public int OrdersArchiveId { get; set; }
        public string UserId { get; set; }
        public List<Order> Orders { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

ArdelsCakeShop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ArdelsCakeShop.Controllers.Utilities;
using ArdelsCakeShop.Models.Cakes;
using ArdelsCakeShop.Models.IdentityModel;
using ArdelsCakeShop.Models.Orders;
using ArdelsCakeShop.Models.Repository;
using ArdelsCakeShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace ArdelsCakeShop.Controllers
{

    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IOrderRepository _orderRepository;
        private readonly ICakeRepository _cakeRepository;
        private readonly IOrdersArchiveRepository _ordersArchiveRepository;        

        public AdminController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager,
            IOrderRepository orderRepository, ICakeRepository cakeRepository, IOrdersArchiveRepository ordersArchiveRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _orderRepository = orderRepository;
            _cakeRepository = cakeRepository;
            _ordersArchiveRepository = ordersArchiveRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UserManagement()
        {
            var users = _userManager.Users;

            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return RedirectToAction("UserManagement", _userManager.Users);
            }

            var editUser = new EditUserViewModel
            {
                Email = user.Email,
                UserName = user.UserName,
                Id = user.Id
            };           

            return View(editUser);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel userViewModel)
        {
            var user = await _userManager.FindByIdAsync(userViewModel.Id);

            if (user != null)
            {
                user.Email = userViewModel.Email;
                user.UserName = userViewModel.UserName;

                var editUser = new EditUserViewModel
                {
                    Email = user.Email,
                    UserName = user.UserName,
                    Id = user.Id
                };

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                    return RedirectToAction("UserManagement", _userManager.Users);

                ModelState.AddModelError("", "User not updated, something went wrong.");

                return View(editUser);
            }

            return RedirectToAction("UserManagement", _userManager.Users);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("UserManagement");
                else
                    ModelState.AddModelError("", "Something went wrong while deleting this user.");
            }
            else
            {
                ModelState.AddModelError("", "This user can't be found");
            }
            return View("UserManagement", _userManager.Users);
        }

        public IActionResult RoleManagement()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(AddRoleViewModel addRoleViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addRoleViewModel);
            }

            var role = new IdentityRole
            {
                Name = addRoleViewModel.RoleName
            };

            var result = await _roleManager.CreateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(addRoleViewModel);
        }

        public IActionResult BackToRoleManagement()
        {
            return RedirectToAction("RoleManagement", _roleManager.Roles);
        }

        public async Task<IActionResult> EditRole(String id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ModelState.AddModelError("", "This role can't be found or edited.");
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }
                

            var editRoleViewModel = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name,
                Users = new List<string>()
            };


            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                    editRoleViewModel.Users.Add(user.UserName);
            }

            return View(editRoleViewModel);

        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel editRoleViewModel)
        {
            var role = await _roleManager.FindByIdAsync(editRoleViewModel.Id);

            if (role != null && !role.Name.Equals("Administrator"))
            {
                role.Name = editRoleViewModel.RoleName;

                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("RoleManagement", _roleManager.Roles);

                ModelState.AddModelError("", "We're sorry, but role cannot be updated");

                return View(editRoleViewModel);
            }

            ModelState.AddModelError("", "This role can't be found or edited.");
            return RedirectToAction("RoleManagement", _roleManager.Roles);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null && !role.Name.Equals("Administrator"))
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("RoleManagement", _roleManager.Roles);
                ModelState.AddModelError("", "Something went wrong while deleting this role.");
            }
            else
            {
                ModelState.AddModelError("", "This role can't be found or deleted.");
            }
            return View("RoleManagement", _roleManager.Roles);
        }


        public async Task<IActionResult> AddUserToRole(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
                return RedirectToAction("RoleManagement", _roleManager.Roles);

            var addUserToRoleViewModel = new UserToRoleViewModel
            {
                RoleId = role.Id,
                Users = new List<ApplicationUser>()
            };

            foreach (var user in _userManager.Users)
            {
                if (!await _userManager.IsInRoleAsync(user, role.Name))
                {
                    addUserToRoleViewModel.Users.Add(user);
                }
            }

            return View(addUserToRoleViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToRole(UserToRoleViewModel userRoleViewModel)
        {
            if (userRoleViewModel.RoleId == null)
            {
                ModelState.AddModelError("", "Role not specified.");
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }

            var role = await _roleManager.FindByIdAsync(userRoleViewModel.RoleId);

            if (role == null)
            {
                ModelState.AddModelError("", "Users or role not specified.");
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }

            else if (userRoleViewModel.UserId == null)
            {
                ModelState.AddModelError("", "User not specified.");
                return RedirectToAction("AddUserToRole", userRoleViewModel.RoleId);
            }
            
            var user = await _userManager.FindByIdAsync(userRoleViewModel.UserId);

            if (user == null)
            {
                ModelState.AddModelError("", "User not specified.");
                return RedirectToAction("AddUserToRole", userRoleViewModel.RoleId);
            }            

            var result = await _userManager.AddToRoleAsync(user, role.Name);

            var addUserToRoleViewModel = new UserToRoleViewModel
            {
                RoleId = role.Id,
                Users = new List<ApplicationUser>()
            };

            foreach (var us in _userManager.Users)
            {
                if (!await _userManager.IsInRoleAsync(us, role.Name))
                {
                    addUserToRoleViewModel.Users.Add(us);
                }
            }

            if (result.Succeeded)
            {                
                return View(addUserToRoleViewModel);
            }

ArdelsCakeShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ArdelsCakeShop.Controllers.Utilities;
using ArdelsCakeShop.Models.IdentityModel;
using ArdelsCakeShop.Models.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ArdelsCakeShop.Models.Orders;
using ArdelsCakeShop.ViewModels;
using Microsoft.AspNetCore.Authorization;


namespace ArdelsCakeShop.Controllers
{
    public class OrderController: Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IOrdersArchiveRepository _ordersArchiveRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly EmailSender _emailSender;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public OrderController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager,
            IOrderRepository orderRepository, ShoppingCart shoppingCart, IOrdersArchiveRepository ordersArchiveRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _orderRepository = orderRepository;
            _ordersArchiveRepository = ordersArchiveRepository;
            _shoppingCart = shoppingCart;
        }
        [Authorize]
        public async Task<IActionResult> Archive()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new OrdersArchiveViewModel();

            if (User.IsInRole("Administrator"))
            {
                var entireArchive = _ordersArchiveRepository.GetArchives();

                if (entireArchive != null)
                {
                    var orders = new List<Order>();

                    var ordersArchives = entireArchive.ToList();
                    foreach (var oa in ordersArchives)
                    {
                        orders.AddRange(oa.Orders);
                    }

                    model.Orders = orders;
                }
                else
                {
                    model.Orders = new List<Order>();
                }

                return View(model);
            }
            var archive = _ordersArchiveRepository.GetArchiveByUserId(user.Id);

            model.Orders = archive != null ? archive.Orders : new List<Order>();

            return View(model);
        }

        public async Task<IActionResult> Checkout()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (user != null)
            {
                var model = new Order
                {
                    AddressLine = user.Address,
                    PhoneNumber = user.PhoneNumber,
                    Email = user.Email
                };
                return View(model);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {                        
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some cakes.");
            }

            if (ModelState.IsValid)
            {
                order.ConfirmationToken = Guid.NewGuid().ToString();
                var link = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}" + "/Order/ConfirmOrder?token=" + order.ConfirmationToken;
                
                // place the order
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();

                //notify admins that a new order has been placed
                var role = await _roleManager.FindByNameAsync("Administrator");
                var admins = new List<ApplicationUser>();
                
                foreach (var user in _userManager.Users)
                {
                    if (await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        admins.Add(user);
                    }
                }

                var client = new ApplicationUser
                {
                    Email = order.Email,
                    Address = order.AddressLine,                    
                    PhoneNumber = order.PhoneNumber
                };


                var emailSender = EmailSender.Instance;
                emailSender.NotifyAdminsNewOrder(order, admins);
                emailSender.NotifyClientNewOrder(order, client, link);                

                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }              

        public IActionResult CheckoutComplete()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmOrder(string token)
        {
            var order = _orderRepository.GetOrders().AsQueryable().FirstOrDefault(o => o.ConfirmationToken == token);

            var model = new ConfirmOrderViewModel();
            
            if (order != null)
            {
                order.OrderState = OrderState.Accepted;
                order.ConfirmationToken = null;
                _orderRepository.Update(order);

                var role = await _roleManager.FindByNameAsync("Administrator");
                var admins = new List<ApplicationUser>();

                foreach (var user in _userManager.Users)
                {
                    if (await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        admins.Add(user);
                    }
                }

                var emailSender = EmailSender.Instance;

                model.Message = "You're order has been accepted!";
                emailSender.NotifyAdminsConfirmedOrder(order, admins);


                // add order to archive
                var client = await _userManager.FindByEmailAsync(order.Email);

                if (client != null)
                {
                    _ordersArchiveRepository.AddOrderToArchiveByUserId(client.Id, order);
                }

                return View(model);
            }

            model.Message = "This link is not valid any longer!";            

            return View(model);           
        }

    }
}

ArdelsCakeShop/Views/Order/Archive.cshtml
@model OrdersArchiveViewModel
@{
    ViewData["Title"] = "Archive";
}


@if (Model.Orders.Count > 0)
{
    int count = 0;
    <h3>Orders:</h3>
    <div class="order-list list-group">

        @foreach (var order in Model.Orders)
        {
            count++;
            <div class="order-item text-center">
                <a class="btn active collapseDetails" href="@("#collapseDetails" + order.OrderId)" role="button"
                   data-toggle="collapse" aria-expanded="false">
                    <span class="pull-left">Order</span>
                    <span># @count</span>
                    <span class="pull-right">@order.OrderState</span>
                </a>
                <div class="collapse" id="@("collapseDetails" + order.OrderId)">
                    <form>
                        <div class="form-group list-group-item row ">
                            <div class="col-md-4">
                                <label for="fullName">FullName:</label>
                                <input type="text" readonly class="form-control" id="fullName" value="@(@order.FirstName + " " + @order.LastName)" />
                            </div>
                            <div class="col-md-4">
                                <label for="email">Email:</label>
                                <input type="text" readonly class="form-control " id="email" value="@order.Email" />
                            </div>
                        </div>

                        <div class="form-group list-group-item row ">
                            <div class="col-md-4">
                                <label for="phone-number">Phone number:</label>
                                <input type="text" readonly class="form-control" id="phone-number" value="@order.PhoneNumber" />
                            </div>
                            <div class="col-md-4">
                                <label for="address1">Address:</label>
                                <input type="text" readonly class="form-control" id="address1" value="@order.AddressLine" />
                            </div>
                        </div>

                        <div class="form-group list-group list-group-item row ">
                            <a class="btn active collapseCakeDetails" href="@("#collapseCakeDetails" + order.OrderId)" role="button"
                               data-toggle="collapse" aria-expanded="false">
                                Cakes
                            </a>
                            <div class="collapse" id="@("collapseCakeDetails" + order.OrderId)">
                                @{
                                    foreach (var orderDetail in order.OrderLines)
                                    {
                                        <div class="form-group list-group-item row">
                                            <div class="col-md-4">
                                                <label for="cakeName">Cake:</label>
                                                <input type="text" readonly class="form-control" id="cakeName" value="@orderDetail.Cake.Name" />
                                            </div>
                                            <div class="col-md-4">
                                                <label for="amount">Amount:</label>
                                                <input type="text" readonly class="form-control" id="amount" value="@orderDetail.Amount" />
                                            </div>
                                            <div class="col-md-4">
                                                <label for="price">Price:</label>
                                                <input type="text" readonly class="form-control" id="price" value="@orderDetail.Price" />
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                        <div class="form-group list-group-item row ">
                            <div class="col-md-4">
                                <label for="order-placed">Order placed:</label>
                                <input type="text" readonly class="form-control" id="order-placed" value="@order.OrderPlaced" />
                            </div>
                            <div class="col-md-4">
                                <label for="order-total">Order total:</label>
                                <input type="text" readonly class="form-control" id="order-total" value="@order.OrderTotal" />
                            </div>
                            
                            @if (User.IsInRole("Administrator"))
                            {
                                <div class="col-md-4">
                                    <button class="btn bg-danger" type="submit"
                                            asp-route-id="@order.OrderId" asp-controller="Admin" asp-action="RemoveOrder">
                                        Remove
                                    </button>                                    
                                </div>

                            }
                            
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
}
else
{
    <h3>There is no order in the archive!</h3>
}

ArdelsCakeShop/Views/Order/Checkout.cshtml
@model ArdelsCakeShop.Models.Orders.Order

<form asp-controller="Order" asp-action="Checkout" method="post" class="form-horizontal" role="form">
    <h3>You're just one step away from your delicious cakes.</h3>
    
    <h5>Make sure your details are corect.</h5>
        
    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="AddressLine" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="AddressLine" class="form-control"  value="@Model.AddressLine"/>
            <span asp-validation-for="AddressLine" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="PhoneNumber" class="form-control" value="@Model.PhoneNumber"/>
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Email" class="form-control" value="@Model.Email"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>


    <div class="text-left">
        <button type="submit" class="btn btn-primary">Complete order</button>
    </div>

</form>

ArdelsCakeShop/Views/Order/CheckoutComplete.cshtml
<h2>Your order was successfully placed.</h2>
<br/>
<br/>

<div class="isa_info ">
    
        We'll send you an email with order details and a <strong>confirmation link</strong> very soon!<br />
        Make sure you follow the link to confirm the order!<br />
        Thank you!
    
</div>

ArdelsCakeShop/Views/Order/ConfirmOrder.cshtml
@model ConfirmOrderViewModel
@{
    ViewData["Title"] = "ConfirmOrder";
}

<h2>@Model.Message</h2>