ArdelsCakeShop/ViewModels/AddRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ArdelsCakeShop.ViewModels
{
    public class AddRoleViewModel
    {
        [Required]
        [Display(Name = "Role name")]
        [StringLength(100)]
        public string RoleName { get; set; }
    }
}

ArdelsCakeShop/ViewModels/EditRoleViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ArdelsCakeShop.ViewModels
{
    public class EditRoleViewModel
    {
        [Required]
        [StringLength(100)]
        public string Id { get; set; }
        [Required]
        [StringLength(100)]
        public string RoleName { get; set; }
        public List<string> Users { get; set; }
    }
}

ArdelsCakeShop/ViewModels/EditUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ArdelsCakeShop.ViewModels
{
    public class EditUserViewModel
    {
        [Required]
        [StringLength(100)]
        public string Id { get; set; }
        [Required]
        [StringLength(100)]
        public string UserName { get; set; }
        [EmailAddress]
        [StringLength(100)]
        public string Email { get; set; }
    }
}

ArdelsCakeShop/ViewModels/UpdateImageViewModel.cs
using Microsoft.AspNetCore.Http;

namespace ArdelsCakeShop.ViewModels
{
    public class UpdateImageViewModel
    {
        public string SmallImage { get; set; }
        public IFormFile FormFile { get; set; }
        public int CakeId { get; set; }
    }
}

ArdelsCakeShop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ArdelsCakeShop.Controllers.Utilities;
using ArdelsCakeShop.Models.Cakes;
using ArdelsCakeShop.Models.IdentityModel;
using ArdelsCakeShop.Models.Orders;
using ArdelsCakeShop.Models.Repository;
using ArdelsCakeShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace ArdelsCakeShop.Controllers
{

    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IOrderRepository _orderRepository;
        private readonly ICakeRepository _cakeRepository;
        private readonly IOrdersArchiveRepository _ordersArchiveRepository;        

        public AdminController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager,
            IOrderRepository orderRepository, ICakeRepository cakeRepository, IOrdersArchiveRepository ordersArchiveRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _orderRepository = orderRepository;
            _cakeRepository = cakeRepository;
            _ordersArchiveRepository = ordersArchiveRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UserManagement()
        {
            var users = _userManager.Users;

            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return RedirectToAction("UserManagement", _userManager.Users);
            }

            var editUser = new EditUserViewModel
            {
                Email = user.Email,
                UserName = user.UserName,
                Id = user.Id
            };           

            return View(editUser);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel userViewModel)
        {
            var user = await _userManager.FindByIdAsync(userViewModel.Id);

            if (user != null)
            {
                user.Email = userViewModel.Email;
                user.UserName = userViewModel.UserName;

                var editUser = new EditUserViewModel
                {
                    Email = user.Email,
                    UserName = user.UserName,
                    Id = user.Id
                };

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                    return RedirectToAction("UserManagement", _userManager.Users);

                ModelState.AddModelError("", "User not updated, something went wrong.");

                return View(editUser);
            }

            return RedirectToAction("UserManagement", _userManager.Users);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("UserManagement");
                else
                    ModelState.AddModelError("", "Something went wrong while deleting this user.");
            }
            else
            {
                ModelState.AddModelError("", "This user can't be found");
            }
            return View("UserManagement", _userManager.Users);
        }

        public IActionResult RoleManagement()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(AddRoleViewModel addRoleViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(addRoleViewModel);
            }

            var role = new IdentityRole
            {
                Name = addRoleViewModel.RoleName
            };

            var result = await _roleManager.CreateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(addRoleViewModel);
        }

        public IActionResult BackToRoleManagement()
        {
            return RedirectToAction("RoleManagement", _roleManager.Roles);
        }

        public async Task<IActionResult> EditRole(String id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ModelState.AddModelError("", "This role can't be found or edited.");
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }
                

            var editRoleViewModel = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name,
                Users = new List<string>()
            };


            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                    editRoleViewModel.Users.Add(user.UserName);
            }

            return View(editRoleViewModel);

        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel editRoleViewModel)
        {
            var role = await _roleManager.FindByIdAsync(editRoleViewModel.Id);

            if (role != null && !role.Name.Equals("Administrator"))
            {
                role.Name = editRoleViewModel.RoleName;

                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("RoleManagement", _roleManager.Roles);

                ModelState.AddModelError("", "We're sorry, but role cannot be updated");

                return View(editRoleViewModel);
            }

            ModelState.AddModelError("", "This role can't be found or edited.");
            return RedirectToAction("RoleManagement", _roleManager.Roles);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null && !role.Name.Equals("Administrator"))
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("RoleManagement", _roleManager.Roles);
                ModelState.AddModelError("", "Something went wrong while deleting this role.");
            }
            else
            {
                ModelState.AddModelError("", "This role can't be found or deleted.");
            }
            return View("RoleManagement", _roleManager.Roles);
        }


        public async Task<IActionResult> AddUserToRole(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
                return RedirectToAction("RoleManagement", _roleManager.Roles);

            var addUserToRoleViewModel = new UserToRoleViewModel
            {
                RoleId = role.Id,
                Users = new List<ApplicationUser>()
            };

            foreach (var user in _userManager.Users)
            {
                if (!await _userManager.IsInRoleAsync(user, role.Name))
                {
                    addUserToRoleViewModel.Users.Add(user);
                }
            }

            return View(addUserToRoleViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToRole(UserToRoleViewModel userRoleViewModel)
        {
            if (userRoleViewModel.RoleId == null)
            {
                ModelState.AddModelError("", "Role not specified.");
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }

            var role = await _roleManager.FindByIdAsync(userRoleViewModel.RoleId);

            if (role == null)
            {
                ModelState.AddModelError("", "Users or role not specified.");
                return RedirectToAction("RoleManagement", _roleManager.Roles);
            }

            else if (userRoleViewModel.UserId == null)
            {
                ModelState.AddModelError("", "User not specified.");
                return RedirectToAction("AddUserToRole", userRoleViewModel.RoleId);
            }
            
            var user = await _userManager.FindByIdAsync(userRoleViewModel.UserId);

            if (user == null)
            {
                ModelState.AddModelError("", "User not specified.");
                return RedirectToAction("AddUserToRole", userRoleViewModel.RoleId);
            }            

            var result = await _userManager.AddToRoleAsync(user, role.Name);

            var addUserToRoleViewModel = new UserToRoleViewModel
            {
                RoleId = role.Id,
                Users = new List<ApplicationUser>()
            };

            foreach (var us in _userManager.Users)
            {
                if (!await _userManager.IsInRoleAsync(us, role.Name))
                {
                    addUserToRoleViewModel.Users.Add(us);
                }
            }

            if (result.Succeeded)
            {                
                return View(addUserToRoleViewModel);
            }

ArdelsCakeShop/Controllers/UploadCakeController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using ArdelsCakeShop.Models.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ArdelsCakeShop.Controllers
{
    public class UploadCakeController : Controller
    {


        private readonly ICakeRepository _cakeRepository;
        private readonly IHostingEnvironment _hostingEnvironment;

        public UploadCakeController(ICakeRepository cakeRepository, IHostingEnvironment hostingEnvironment)
        {
            _cakeRepository = cakeRepository;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Upload(IFormFile formFile, int cakeId)
        {
            if (formFile == null || cakeId == 0)
            {
                return RedirectToAction("CakeManagement", "Admin",_cakeRepository.GetAllCakes());
            }

            var cake = _cakeRepository.GetCakeById(cakeId);
            // process uploaded files
            var dotSplitted = formFile.FileName.Split('.');
            var ext = dotSplitted[dotSplitted.Length - 1];

            if (ext.Equals("jpg") || ext.Equals("png"))
            {
                string webRootPath = _hostingEnvironment.WebRootPath.Replace("\\", "/");
                var imagesPath = Startup.HiddenKeys["ImagesPath"];
                var myUniqueFileName = string.Format(@"{0}.{1}", Guid.NewGuid(), ext);

                var relativePath = imagesPath + myUniqueFileName;
                var filePath = webRootPath + relativePath;

                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }

                    if (cake.SmallImage != null)
                    {
                        try
                        {
                            var oldFile = webRootPath + cake.SmallImage;
                            System.IO.File.Delete(oldFile);
                        }
                        catch (Exception e)
                        {
                            ModelState.AddModelError("", "Something went wrong uploading the new cake.");
                            return RedirectToAction("EditCake", "Admin", cake);
                        }
                    }
                    
                    cake.SmallImage = relativePath;
                    _cakeRepository.Update(cake);

                    return RedirectToAction("EditCake", "Admin", cake);

                }
            }
            else
            {
                ModelState.AddModelError("", "Picture extension not available, please use jpg or png.");
            }
            return RedirectToAction("EditCake", "Admin", cake);
        }
    }
}

ArdelsCakeShop/Views/Admin/AddCake.cshtml
@using ArdelsCakeShop.Models.Cakes
@model ArdelsCakeShop.Models.Cakes.Cake

@{
    ViewData["Title"] = "AddCake";
}

<h2>AddCake</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCake" asp-controller="Admin">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>                
                <textarea asp-for="Description" class="form-control"cols="20" rows="4" runat="server"></textarea>                            
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeStatus" class="control-label"></label>
                <select asp-for="CakeStatus"
                        asp-items="@(Html.GetEnumSelectList<CakeStatus>())"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="CakeManagement">Back to List</a>
</div>

ArdelsCakeShop/Views/Admin/AddRole.cshtml
@model AddRoleViewModel

<form asp-controller="Admin" asp-action="AddRole" method="post" class="form-horizontal">
    <h4 class="text-center">Enter the role details:</h4>

    <div class="form-group">
        <label asp-for="RoleName" class="col-sm-3 control-label"></label>
        <div class="col-sm-6">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            <button type="submit" class="btn btn-primary">
                Create
            </button>
            <span>
                <button type="submit" class="btn btn-danger" asp-controller="Admin" asp-action="BackToRoleManagement">
                    Cancel
                </button>
            </span>
        </div>
        
    </div>
</form>

ArdelsCakeShop/Views/Admin/AddUser.cshtml
@{
    ViewData["Title"] = "AddUser";
}

<h2>AddUser</h2>

ArdelsCakeShop/Views/Admin/AddUserToRole.cshtml
@model UserToRoleViewModel

@if (Model.Users.Count > 0)
{
    <h2>Promote user to a new role:</h2>
    <form class="form-group" asp-controller="Admin" asp-action="AddUserToRole" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" name="RoleId" value="@Model.RoleId" />
        <select class="form-control" asp-for="UserId"
                asp-items="@(new SelectList(Model.Users, "Id", "UserName"))"></select>
        <button class="btn btn-primary" type="submit">
            Confirm
        </button>
    </form>
}
else
{
    <h2 class="text-info">No user to promote.</h2>
}

<div>
    <a asp-action="RoleManagement" class="btn btn-default">Back to role management</a>
</div>
<div>
    <a asp-action="EditRole" asp-route-id="@Model.RoleId" class="btn btn-default">Back to edit</a>
</div>

ArdelsCakeShop/Views/Admin/CakeManagement.cshtml
@model IEnumerable<ArdelsCakeShop.Models.Cakes.Cake>

@{
    ViewData["Title"] = "Cake Managemenet";
}

<h2>Cake Managemenet</h2>

<a asp-controller="Admin" asp-action="AddCake" class="btn btn-primary">Add a new cake</a>
<div asp-validation-summary="All" class="text-info" id="warning"></div>
<h4>List of cakes:</h4>
<table class="table table-bordered table-responsive cakes-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Status</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cake in Model)
        {
            <tr>
                <td>@cake.Name</td>
                <td>@cake.Description</td>
                <td>@cake.Price</td>
                <td>@cake.CakeStatus</td>
                <td><img src="@cake.SmallImage" alt="@cake.Name" /></td>
                <td>
                    <div>
                        <a asp-controller="Admin" asp-action="EditCake" asp-route-id="@cake.Id" class="btn btn-default">Edit</a>
                        <a asp-controller="Admin" asp-action="RemoveCake" asp-route-id="@cake.Id"
                            onclick="return confirm('Do you want to remove this cake?')" class="btn btn-default">Remove</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ArdelsCakeShop/Views/Admin/DeleteUserFromRole.cshtml
@model UserToRoleViewModel



@if (Model.Users.Count > 0)
{
    <h2>Remove user from role:</h2>
    <form  class="form-group" asp-controller="Admin" asp-action="DeleteUserFromRole" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" name="RoleId" value="@Model.RoleId" />
        <select class="form-control" asp-for="UserId"
                asp-items="@(new SelectList(Model.Users, "Id", "UserName"))">            
        </select>
        <button class="btn btn-primary" type="submit">
            Confirm
        </button>
    </form>
}
else
{
    <h2 class="text-info">No user to remove.</h2>
}
<div>
    <a asp-action="RoleManagement" class="btn btn-default">Back to role management</a>
</div>
<div>
    <a asp-action="EditRole" asp-route-id="@Model.RoleId" class="btn btn-default">Back to edit</a>
</div>

ArdelsCakeShop/Views/Admin/EditCake.cshtml
@using ArdelsCakeShop.Models.Cakes
@model ArdelsCakeShop.Models.Cakes.Cake

@{
    ViewData["Title"] = "Edit Cake";
}

<h2>Edit cake or upload a new image</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCake" asp-controller="Admin" >
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"cols="20" rows="4" runat="server"></textarea>                            
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeStatus" class="control-label"></label>
                <select asp-for="CakeStatus"
                        asp-items="@(Html.GetEnumSelectList<CakeStatus>())">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SmallImage" class="control-label"></label>
                <img src="@Model.SmallImage"/>
                <span asp-validation-for="SmallImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                
            </div>
        </form>
    </div>  
</div>

<div class="row">
    <div class="col-sm-2">
        <a class="btn btn-default" asp-action="CakeManagement">Back to list</a>
    </div>
    <div class="col-sm-2">
        <a class="btn btn-primary" asp-controller="Admin" asp-action="UpdateImage" asp-route-id="@Model.Id">Upload a new image</a>
    </div>
</div>

ArdelsCakeShop/Views/Admin/EditRole.cshtml
@model EditRoleViewModel

<h2>Edit role</h2>

<form asp-controller="Admin" asp-action="EditRole" method="post" class="form-horizontal" role="form">

    <div class="form-group">
        <label asp-for="Id" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Id" class="form-control" readonly="readonly" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="RoleName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Save role" />
            <a asp-action="RoleManagement" class="btn btn-danger">Cancel</a>
        </div>
    </div>
</form>

@if (!Model.Users.Any())
{
    <h3>No user defined to this role.</h3>

}
else
{
    <div>
        <h3>Users in this role</h3>
        <ul class="list-group">
            @foreach (var user in Model.Users)
        {
            <li class="list-group-item">
                @user
            </li>
        }
        </ul>
    </div>
}

<a asp-action="AddUserToRole" asp-route-roleId="@Model.Id" class="btn btn-primary">Add users to role</a>
<a asp-action="DeleteUserFromRole" asp-route-roleId="@Model.Id" class="btn btn-primary">Remove users from role</a>

ArdelsCakeShop/Views/Admin/EditUser.cshtml
@model EditUserViewModel

<h2>Edit user</h2>

<form asp-controller="Admin" asp-action="EditUser" method="post" class="form-horizontal" role="form">

    <div class="form-group">
        <label asp-for="Id" class="col-md-2 control-label"></label>
        <div class="col-md-4">
            <input asp-for="Id" class="form-control" readonly="readonly" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="UserName" class="col-md-2 control-label"></label>
        <div class="col-md-4">
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-4">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" class="btn btn-primary" value="Save" />
            <a asp-action="UserManagement" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>

ArdelsCakeShop/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

ArdelsCakeShop/Views/Admin/RoleManagement.cshtml
@model IEnumerable<IdentityRole>

<h2>Roles management</h2>

<div class="text-danger" asp-validation-summary="All"></div>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">No roles defined yet.</td></tr>
}
else
{
    <table class="table table-bordered">
        <tr>
            <th>Role ID</th>
            <th>Role name</th>
            <th>Actions</th>
        </tr>
        @foreach(var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td>
                    <form asp-action="DeleteRole" asp-route-id="@role.Id" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditRole" asp-route-id="@role.Id">Edit role</a>
                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Do you want to delete this role?')">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>

        }

    </table>
}
<a class="btn btn-primary" asp-action="AddRole">Add new role</a>

ArdelsCakeShop/Views/Admin/UpdateImage.cshtml
@model UpdateImageViewModel
@{
    ViewData["Title"] = "UpdateImage";
}
<h2>Upload new image</h2>

<h4>@ViewData["HeaderInfo"]</h4>
<form asp-controller="UploadCake" asp-action="Upload"
      method="POST" enctype="multipart/form-data">

    <div class="form-group">
        <label asp-for="SmallImage" class="control-label">Current image</label>
        <img src="@Model.SmallImage"/>
        <span asp-validation-for="SmallImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div>
            <label asp-for="FormFile">Upload a new image:</label>
            <input asp-for="FormFile" class="btn btn-default" type="file"/>
            <input type="hidden" asp-for="CakeId" value="@Model.CakeId"/>
        </div>
    </div>
    <div class="form-group">
        <div>
            <button type="submit" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-upload"></span> Upload
            </button>
        </div>
    </div>
</form>

<div>
    <a class="btn btn-default" asp-controller="Admin" asp-action="CakeManagement">Back to list</a>
</div>

ArdelsCakeShop/Views/Admin/UserManagement.cshtml
@model IEnumerable<ApplicationUser>


<h2>Users management</h2>

@if (!Model.Any())
{
    <tr><td colspan="3" class="text-center">No User Accounts</td></tr>
}
else
{
    <table class="table table-condensed table-bordered" header header-content="User Management">
        <tr>
            <th>User ID</th>
            <th>UserName</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
        @foreach(var user in @Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <form asp-action="DeleteUser" asp-route-userId="@user.Id" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditUser"
                           asp-route-id="@user.Id">Edit</a>
                        <button type="submit" onclick="return confirm('Are you sure you want to delete this user?')" class="btn btn-primary">
                            Delete
                        </button>
                    </form>
                          
                </td>
            </tr>

        }

    </table>

}